apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
      #   volumeMounts:
      #   - name: scripts-vol
      #     mountPath: /scripts-dir        
      # volumes:
      # - name: scripts-vol
      #   configMap:
      #     name: postgres-setup  
      restartPolicy: Always



       

